steps:

steps:
  # install dependencies
  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "-c", "constraints.txt", "--user"]

  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  # run in python 3.8 which is latest version in Cloud Composer
  - name: python:3.8-slim
    entrypoint: python3.8
    args: ["-m", "pytest", "-s", "dags/"]

  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user"]
    
  - name: 'gcr.io/$PROJECT_ID/python-cloudbuild' 
    entrypoint: '/bin/bash'
    args: ['-c','virtualenv /workspace/venv' ]
    
  - name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
    entrypoint: 'venv/bin/pip'
    args: ['install', '-V', '-r', 'requirements1.txt']
    
  - name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
    entrypoint: 'venv/bin/python'
    args: ['-m', 'pytest' , '--cov=utils','--cov-report=xml','-v']

#   # install coverage
#   - name: python
#     entrypoint: pip
#     args: ["install","coverage"]

#   # install coverage
#   - name: python
#     entrypoint: python
#     args:
#       - '-c'
#       - |
#       - coverage run *.py
#       - coverage xml

#   - name: python:3.7
#     entrypoint: python3
#     id: RUN-COVERAGE-TESTS
#     args:
#       - '-c'
#       - python3 -m pytest --cov=tests/ --cov-report xml:coverag1.xml


  # Static code Analysis
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://35.200.250.32:9000 '
    - '-Dsonar.login=sqp_78d4c4d00e71fc99a703f80d38fee3b6618ee95a'
    - '-Dsonar.projectKey=sonar-test-1 '
    - '-Dsonar.sources=.'
    - '-Dsonar.python.coverage.reportPaths=coverage.xml'


